### PR TITLE
Adding several new functionalities

### PR DESCRIPTION
**Pull request by skpalan**
Hi Velina,

I am adding several new functionalities at the same time, including:
1. `imputeKNN`: new test cases and algorithm;
2. `runWilcoxon`: a function to run the Wilcoxon test;
3. `linkGenesAndPeaks`: calculates the correlation between genes and peaks;
4. `makeInteractTrack`: exports the results from `linkGenesAndPeaks` to a UCSC Interact Track file;
5. `quantile_norm`: A substitution function of `quantileAlignSNF`;
6. `louvainCluster`: performs Louvain clustering;

All of these functions are mentioned and utilized in the new tutorial. We will be pretty excited to see them in the package!
Many thanks!

### CODE REVIEW

**Comment by vkozareva** [comment]
Hey Jialin! Looks great at first glance. I haven't been able to test all the new functionality myself but am glad you added the extra tests from before. 

Before we merge this in though, could you make sure to increment the version number to ***0.5.0*** so that we can more easily track any potential bugs that result? Also if you could add a git tag/release reflecting the new version that would be great (I can show you how to do this if necessary).

**Comment by skpalan** [comment]
Hi Velina, that's a great idea! I have created a new git release *v0.5.9000* as a pre-release for the new version. Please give a check when convenient. Many thanks!

**Comment by vkozareva** [comment]
Thanks for adding the tag! @skpalan One note for the future -- we should wait until the branch is merged into master and **then** add the tag/create the release so the new functionality is included! Edited the tag/release to address https://github.com/MacoskoLab/liger/issues/146.

**Comment by skpalan** [comment]
Sorry for that release note -- I thought we just need a place holder for the new version. Nice to get some experience in release/tag management! And many thanks for addressing that issue!

**Pull request merged**
