### PR TITLE
Change some functions into S3 generics and methods

### PR DESCRIPTION
**Pull request by mojaveazure**
Hi Velina, Josh, and Evan,

I've modified some functions in LIGER (`optimizeALS`, `SNF` and `quantileAlignSNF`) into [S3 methods and generics](http://adv-r.had.co.nz/S3.html). What this means is that rather than expecting a `liger` object, these functions now evaluate the class of the object provided and do something based on that class. The calling of the function hasn't changed (users will still call `optimizeALS`, `SNF` or `quantileAlignSNF`), but R will now figure out what to do based on the class of object provided.

For this PR, I've made two methods for each function, one for `liger` objects and one for lists of matrices. What happens here is you'll call one of these functions (eg. `quantileAlignSNF`) on a `liger` object and R will call the `liger`-specific method for that function (eg. `quantileAlignSNF.liger`). The `liger` methods simply pull data from a `liger` object and feed it on to the list method (eg. `quantileAlignSNF.list`). The list method does all the computation, then returns data back to the `liger` method, which in turn stores the results in the `liger` object and returns said object.

image

Again, this doesn't change how the user uses LIGER, they'll still call `quantileAlignSNF` and not have to worry about which method is doing what. The biggest benefit to this is to allow other developers to build new methods for your tools; these methods would simply serve to pull data from another kind of object (eg. a `Seurat` object), feed it into your list methods, then take the results and store it back in their own object structure. This results in more people being able to use LIGER's functionality without needing to perform costly conversions to and from various objects.

Let me know if you have any questions or concerns; I'd be happy to go over anything I did here in more detail.

### CODE REVIEW

**Comment by MacoskoLab** [comment]
Thanks for doing this @mojaveazure! This looks great, and we should be able to merge this in in the next few days (just want to deploy some unrelated changes on our end first). 

Also thanks for doing a lot of the testing on your own -- we plan to have some unit tests up soon!

**Comment by vkozareva** [comment]
Actually spoke just a bit too soon -- this new NAMESPACE seems to export only the S3 methods and generics, despite the export tags that we've added to most of our other functions. I see that you've generated it with roxygen so I'm not sure why that's happening. Do you know why it might be skipping the other functions? 

Previously we had a catch-all that basically exported everything, but if you know of a way to use roxygen to get a cleaner set of exports, that would obviously be preferable!

**Comment by mojaveazure** [comment]
Hi Velina,

Sorry about that. I had tried to make as few changes to the codebase as possible, and didn't see that you had an `exportPattern` call in your `NAMESPACE`. I've rerun `devtools::document` on it, which now exports anything tagged with `#' @export`, as well as generate documentation based on the other Roxygen tags.

**Comment by vkozareva** [comment]
Hi Paul,
Thanks for making that change! I realize things have gotten kind of mucked up now due to our recent updates. Would it be easier for me to start pushing to your fork to resolve the conflicts? I'm happy to help spare you the rebase.

**Comment by mojaveazure** [comment]
Sure thing; let me know if you need any help dealing with merge conflicts

**Comment by mojaveazure** [comment]
Hi Velina,

I've looked at the merge conflicts that arose from our diverged edits. The only thing that I could really see was some style differences and an internal function rename. I've merged everything and rerun it to ensure it works as expected. Let me know if you notice anything wrong or need anything else.

**Comment by vkozareva** [comment]
Thanks Paul! Just made some minor NAMESPACE changes to keep some of our preprocessing functions working correctly.

**Pull request merged**
